{% set name = "aria2p" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/aria2p-{{ version }}.tar.gz
  sha256: c9d505ae6363092b5ea558160b408677adba876c89a50f9129e7505965e56d00

build:
  entry_points:
    - aria2p = aria2p.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pdm-pep517
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs >=4.2
    - loguru >=0.5
    - requests >=2.19
    - websocket-client >=0.58
    # remove tomli after python_min >=3.11
    - tomli >=2.0

test:
  imports:
    - aria2p
  commands:
    - pip check
    - aria2p --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aria2p/
  summary: Command-line tool and library to interact with an aria2c daemon process with JSON-RPC.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pawamoy
    - holymonson
