{% set name = "aria2p" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aria2p-{{ version }}.tar.gz
  sha256: 1521ccba4a4bb164a023f4c4213513dc3e6f47b91927f5e49dd50678da8c1294

build:
  entry_points:
    - aria2p = aria2p.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pdm-pep517
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs >=4.2
    - loguru >=0.5
    - requests >=2.19
    - toml >=0.10
    - websocket-client >=0.58

test:
  imports:
    - aria2p
  commands:
    - pip check
    - aria2p --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aria2p/
  summary: Command-line tool and library to interact with an aria2c daemon process with JSON-RPC.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pawamoy
    - holymonson
